TOOL_NAME=Selenium
BROWSER_TYPE=Chrome
IS_HEADLESS_MODE=false
LOG_MODE =true
REPORT_CONFIG_PATH=
REPORT_PATH=./reports/
SCREENSHOT_PATH=./reports/screenshots/
MAX_WAIT_TIME=
TESTDATA_FILE_LOCATION=/testdata/TestData.xlsx
TESTDATA_FILE_SHEET_NAME=testdata
